#!/usr/bin/env bash
#Bash script that displays a list of currently running processes.
#Must show all processes, for all users, including those which might not have a TTY-au
#Display in a user-oriented format-f
#Show process hierarchy-x
ps -auxf
