#!/usr/bin/env bash
# This script displays "Best School" and "Hi" at 9th iteration
count="0"
while [ $count -lt 10 ]
do
    echo "Best School"
    if ((count == 8))
    then
        echo "Hi"
    fi
    ((count++))
done
