#!/usr/bin/env bash
# script that loops through 10 iterations and special iterations
count="0"
while [ $count -lt 10 ]
do
	if ((count == 3))
	then
		echo "bad luck"
	elif ((count == 7))
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
